/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { SwipeHandlerStore } from './components/extras/app-swipe/handler';
export namespace Components {
  interface AppArticles {}
  interface AppAuth {}
  interface AppMain {}
  interface AppRoot {}
  interface AppSwipe {
    'handlers': SwipeHandlerStore[];
  }
}
declare global {
  interface HTMLAppArticlesElement
    extends Components.AppArticles,
      HTMLStencilElement {}
  var HTMLAppArticlesElement: {
    prototype: HTMLAppArticlesElement;
    new (): HTMLAppArticlesElement;
  };
  interface HTMLAppAuthElement extends Components.AppAuth, HTMLStencilElement {}
  var HTMLAppAuthElement: {
    prototype: HTMLAppAuthElement;
    new (): HTMLAppAuthElement;
  };
  interface HTMLAppMainElement extends Components.AppMain, HTMLStencilElement {}
  var HTMLAppMainElement: {
    prototype: HTMLAppMainElement;
    new (): HTMLAppMainElement;
  };
  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLAppSwipeElement
    extends Components.AppSwipe,
      HTMLStencilElement {}
  var HTMLAppSwipeElement: {
    prototype: HTMLAppSwipeElement;
    new (): HTMLAppSwipeElement;
  };
  interface HTMLElementTagNameMap {
    'app-articles': HTMLAppArticlesElement;
    'app-auth': HTMLAppAuthElement;
    'app-main': HTMLAppMainElement;
    'app-root': HTMLAppRootElement;
    'app-swipe': HTMLAppSwipeElement;
  }
}
declare namespace LocalJSX {
  interface AppArticles {}
  interface AppAuth {}
  interface AppMain {}
  interface AppRoot {}
  interface AppSwipe {
    'handlers'?: SwipeHandlerStore[];
  }
  interface IntrinsicElements {
    'app-articles': AppArticles;
    'app-auth': AppAuth;
    'app-main': AppMain;
    'app-root': AppRoot;
    'app-swipe': AppSwipe;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'app-articles': LocalJSX.AppArticles &
        JSXBase.HTMLAttributes<HTMLAppArticlesElement>;
      'app-auth': LocalJSX.AppAuth & JSXBase.HTMLAttributes<HTMLAppAuthElement>;
      'app-main': LocalJSX.AppMain & JSXBase.HTMLAttributes<HTMLAppMainElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-swipe': LocalJSX.AppSwipe &
        JSXBase.HTMLAttributes<HTMLAppSwipeElement>;
    }
  }
}
